mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名规则（camel case）映射
  mapper-locations: classpath*:mapper/*
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql
spring:
  datasource:
    url: jdbc:mysql://120.27.128.225:3306/fastdfs?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      #最小空闲连接数
      minimum-idle: 2
      # 连接池最大连接数，默认是10
      maximum-pool-size: 5
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 300000
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 120.27.128.225:22122
